### ISSUE TITLE
请注明非原创内容的来源地址

### ISSUE THREAD

**Issue by ryan4yin** [SJFCS/cloudnative.love#10]
你好，我发现这个站点大量使用了我个人知识库中的文档，而且相当部分的内容都没做任何修改，但并未注明内容来源。

我的知识库地址：

https://github.com/ryan4yin/knowledge

虽然我之前用了 MIT 证书，严格的说这件事并不好判定，但同为内容创作者，我希望你能尊重我的产出，注明这些内容的来源。

以及，我也已经将证书替换成了  [自由转载-非商用-非衍生-保持署名](https://creativecommons.org/licenses/by-nc-nd/4.0/)，后续摘抄我的笔记内容时请注意这一点。

**Comment by SJFCS** [comment]
好的

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ryan Yin ***@***.***>
Sent: Monday, September 2, 2024 11:39:37 AM
To: SJFCS/cloudnative.love ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SJFCS/cloudnative.love] 请注明非原创内容的来源地址 (Issue #10)


你好，我发现这个站点大量使用了我个人知识库中的文档，而且相当部分的内容都没做任何修改，但并未注明内容来源。

我的知识库地址：

https://github.com/ryan4yin/knowledge

虽然我之前用了 MIT 证书，严格的说这件事并不好判定，但同为内容创作者，我希望你能尊重我的产出，注明这些内容的来源。

以及，我也已经将证书替换成了 自由转载-非商用-非衍生-保持署名<https://creativecommons.org/licenses/by-nc-nd/4.0/>，后续摘抄我的笔记内容时请注意这一点。

―

**Comment by ryan4yin** [comment]
@SJFCS 如果你只是想做个人知识库，不想管这些版权问题，我比较建议你不要公开它。
如果公开，就需要考虑这些问题。

既然你自己也是用的 [自由转载-非商用-非衍生-保持署名](https://creativecommons.org/licenses/by-nc-nd/4.0/)，换位思考，我想你应该能理解我现在的心情。

我搜个 istio 的文档，结果一读发现全是我自己写的，还没注明内容来源，这相当尴尬。

**Comment by SJFCS** [comment]
刚刚在路上没时间编辑信息，对不起了 我对此很抱歉，你的文章写的十分好我也很膜拜你。

平时我在blog中自己写一些实践内容输出，在docs自己记录一些知识点，有时会将收集的好文也放在这里面方便分类以及待后续阅读和消化。

本意是打算再看完这些收集来的文章逐渐删掉，自己重新写一些文字输出，因为我不想复制粘贴也不想太拾人牙慧，可奈何没太多时间，久而久之docs里就变得混乱不堪。

由于我的偷懒没有在编译时候注释掉这些文章，所以它们出现在了我的站点上，我再次对此感到抱歉，正好九月我打算对此进行整改。

对于你的这次提醒，今晚我会重新编译将docs的文章访问进行关闭，等待整改完成后再开放。

我也对复制粘贴行为深痛恶绝，但自己在整理资料文档时却却恰恰忽视了这一点，因为一开始我觉得这些文章不会在我的文档中存留许久，会很快的被我阅读并删除。

最后我真挚的再一次对你说一句抱歉，请原谅我。


获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ryan4yin** [comment]
感谢你的及时回复，很高兴你能喜欢我的文章，希望你也能写出更多的好文章~
